dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.41
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  json_serializable: ^6.8.0